#ifndef __RUPA_Warning_Delete_Measurement__
#define __RUPA_Warning_Delete_Measurement__

/**
@file
Subclass of Warning_Delete_Measurement, which is generated by wxFormBuilder.
*/

#include "RUPAUI.h"

//// end generated include

/** Implementing Warning_Delete_Measurement */
class RUPA_Warning_Delete_Measurement : public Warning_Delete_Measurement
{
	protected:
		// Handlers for Warning_Delete_Measurement events.
		void On_Delete( wxCommandEvent& event );
		void On_Cancel( wxCommandEvent& event );
	public:
		/** Constructor */
		RUPA_Warning_Delete_Measurement( wxWindow* parent );
	//// end generated class members




};

#endif // __RUPA_Warning_Delete_Measurement__
