#ifndef __RUPA_Warning_Delete_Campaign__
#define __RUPA_Warning_Delete_Campaign__

/**
@file
Subclass of Warning_Delete_Campaign, which is generated by wxFormBuilder.
*/

#include "RUPAUI.h"

//// end generated include

/** Implementing Warning_Delete_Campaign */
class RUPA_Warning_Delete_Campaign : public Warning_Delete_Campaign
{
	protected:
		// Handlers for Warning_Delete_Campaign events.
		void On_Delete( wxCommandEvent& event );
		void On_Cancel( wxCommandEvent& event );
	public:
		/** Constructor */
		RUPA_Warning_Delete_Campaign( wxWindow* parent );
	//// end generated class members




};

#endif // __RUPA_Warning_Delete_Campaign__
