#ifndef __RUPA_Burst_Editing_Add_Measurement__
#define __RUPA_Burst_Editing_Add_Measurement__

/**
@file
Subclass of Burst_Editing_Add_Measurement, which is generated by wxFormBuilder.
*/

#include "RUPAUI.h"

//// end generated include

/** Implementing Burst_Editing_Add_Measurement */
class RUPA_Burst_Editing_Add_Measurement : public Burst_Editing_Add_Measurement
{
	public:
		/** Constructor */
		RUPA_Burst_Editing_Add_Measurement( wxWindow* parent );
	//// end generated class members
	
};

#endif // __RUPA_Burst_Editing_Add_Measurement__
