#ifndef __RUPA_Change_Validation_State__
#define __RUPA_Change_Validation_State__

/**
@file
Subclass of Change_Validation_State, which is generated by wxFormBuilder.
*/

#include "RUPAUI.h"

//// end generated include

/** Implementing Change_Validation_State */
class RUPA_Change_Validation_State : public Change_Validation_State
{
	protected:
		// Handlers for Change_Validation_State events.
		void On_Yes( wxCommandEvent& event );
		void On_No( wxCommandEvent& event );
	public:
		/** Constructor */
		RUPA_Change_Validation_State( wxWindow* parent );
	//// end generated class members




};

#endif // __RUPA_Change_Validation_State__
