#ifndef __RUPA_Semi_Automatic_Burst__
#define __RUPA_Semi_Automatic_Burst__

/**
@file
Subclass of Semi_Automatic_Burst, which is generated by wxFormBuilder.
*/

#include "RUPAUI.h"
#include "RUPA_Utility.h"
#include "watchdog_pi.h"

//// end generated include
#include "RUPA_Manage_Structure.h"

class RUPA_Manage_Structure;

/** Implementing Semi_Automatic_Burst */
class RUPA_Semi_Automatic_Burst : public Semi_Automatic_Burst
{
    protected:
	// Handlers for Semi_Automatic_Burst events.
	void On_Range_Button( wxCommandEvent& event );
	void On_Battery_Check_Button( wxCommandEvent& event );
	void On_Release_Nut_Button( wxCommandEvent& event );
	void On_Finish_Burst_Button( wxCommandEvent& event );
	void Prepare_SQL();
	wxWindow* parent;

	sql::Driver *driver;
	sql::Connection *con;
	sql::Statement *stmt;
	sql::PreparedStatement *prep_stmt;
	sql::ResultSet *res;
	RUPA_Manage_Structure *l_Manage_Structure;//local variable to interact with window wich called that one
	long int Id_Calling_Structure;
	long int Burst_Id;
    public:
	/** Constructor */
	RUPA_Semi_Automatic_Burst( wxWindow* parent, RUPA_Manage_Structure * MS, bool Recovery );
    //// end generated class members
    private:

	//watchdog_pi &m_watchdog_pi;




};

#endif // __RUPA_Semi_Automatic_Burst__
