#ifndef __RUPA_Warning_Delete_Burst__
#define __RUPA_Warning_Delete_Burst__

/**
@file
Subclass of Warning_Delete_Burst, which is generated by wxFormBuilder.
*/

#include "RUPAUI.h"

//// end generated include

/** Implementing Warning_Delete_Burst */
class RUPA_Warning_Delete_Burst : public Warning_Delete_Burst
{
	protected:
		// Handlers for Warning_Delete_Burst events.
		void On_Delete( wxCommandEvent& event );
		void On_Cancel( wxCommandEvent& event );
	public:
		/** Constructor */
		RUPA_Warning_Delete_Burst( wxWindow* parent );
	//// end generated class members




};

#endif // __RUPA_Warning_Delete_Burst__
