#ifndef __RUPA_Automatic_Burst__
#define __RUPA_Automatic_Burst__

/**
@file
Subclass of Automatic_Burst, which is generated by wxFormBuilder.
*/

#include "RUPAUI.h"
#include "RUPA_Utility.h"

//// end generated include

/** Implementing Automatic_Burst */
class RUPA_Automatic_Burst : public Automatic_Burst
{
	protected:
		// Handlers for Automatic_Burst events.
		void On_Stop_Automatic_Burst( wxCommandEvent& event );
		wxWindow* parent;
	public:
		/** Constructor */
		RUPA_Automatic_Burst( wxWindow* parent , bool Recovery);
	//// end generated class members




};

#endif // __RUPA_Automatic_Burst__
