#ifndef __RUPA_Manage_Structure__
#define __RUPA_Manage_Structure__

/**
@file
Subclass of Manage_Structure, which is generated by wxFormBuilder.
*/

#include "RUPAUI.h"
#include "RUPA_Automatic_Burst.h"
#include "RUPA_Semi_Automatic_Burst.h"
#include "RUPA_Burst_Editing.h"
#include "RUPA_Change_Validation_State.h"
#include "RUPA_Warning_Delete_Burst.h"

//// end generated include

/** Implementing Manage_Structure */
class RUPA_Manage_Structure : public Manage_Structure
{
	protected:
		// Handlers for Manage_Structure events.
		void On_Launch_Auto_Burst( wxCommandEvent& event );
		void On_Launch_Semi_Auto_Burst( wxCommandEvent& event );
		void OnDoubleClick( wxMouseEvent& event );
		void OnLeftDown( wxMouseEvent& event );
		void On_Enter_Burst_Manually( wxCommandEvent& event );
		void On_Edit_burst( wxCommandEvent& event );
		void On_Delete_Burst( wxCommandEvent& event );
		void On_Force_Validation( wxCommandEvent& event );
		void On_Force_Invalidation( wxCommandEvent& event );
		void On_Set_Position_Button( wxCommandEvent& event );
		void On_Launch_Semin_Auto_Burst( wxCommandEvent& event );
		void On_Edit_Burst( wxCommandEvent& event );
		void On_Close( wxCommandEvent& event );
		
		
		RUPA_Automatic_Burst * t_Automatic_Burst;
		RUPA_Semi_Automatic_Burst * t_Semi_Automatic_Burst;
		RUPA_Burst_Editing * t_Burst_Editing;
		RUPA_Warning_Delete_Burst * t_Warning_Delete_Burst;
		RUPA_Change_Validation_State * t_Change_Validation_State;
		wxWindow* parent;
	public:
		/** Constructor */
		RUPA_Manage_Structure( wxWindow* parent );
	//// end generated class members
	
};

#endif // __RUPA_Manage_Structure__
