#ifndef __RUPA_Setup_Structure__
#define __RUPA_Setup_Structure__

/**
@file
Subclass of Setup_Structure, which is generated by wxFormBuilder.
*/

#include "RUPAUI.h"

//// end generated include

/** Implementing Setup_Structure */
#include "RUPA_Manage_Structure.h"

class RUPA_Manage_Structure;
class RUPA_Setup_Structure : public Setup_Structure
{
	protected:
		// Handlers for Setup_Structure events.
		void On_Set_Structure_Settings_Ok( wxCommandEvent& event );
		void On_Set_Structure_Settings_Cancel( wxCommandEvent& event );
	sql::Driver *driver;
	sql::Connection *con;
	sql::Statement *stmt;
	sql::PreparedStatement *prep_stmt;
	RUPA_Manage_Structure *l_Manage_Structure;//local variable to interact with window wich called that one
	long int Id_Calling_Structure;
	public:
		/** Constructor */
		RUPA_Setup_Structure( wxWindow* parent , RUPA_Manage_Structure * MS);
	//// end generated class members


};

#endif // __RUPA_Setup_Structure__
