#ifndef __RUPA_Manage_Transponder__
#define __RUPA_Manage_Transponder__

/**
@file
Subclass of Manage_Transponder, which is generated by wxFormBuilder.
*/

#include "RUPAUI.h"
#include "RUPA_Utility.h"
#include "RUPA_Manage_Structure.h"
//// end generated include

class RUPA_Manage_Structure;
/** Implementing Manage_Transponder */
class RUPA_Manage_Transponder : public Manage_Transponder
{
    protected:
	// Handlers for Manage_Transponder events.
	void On_Accept_Transponder_Edit( wxCommandEvent& event );
	void On_Cancel_Transponder_Edit( wxCommandEvent& event );
	sql::Driver *driver;
	sql::Connection *con;
	sql::Statement *stmt;
	sql::PreparedStatement *prep_stmt;
	RUPA_Manage_Structure *l_Manage_Structure;//local variable to interact with window wich called that one
	long int Id_Calling_Structure;


    public:
	/** Constructor */
	RUPA_Manage_Transponder( wxWindow* parent , RUPA_Manage_Structure * MS);
    //// end generated class members



};

#endif // __RUPA_Manage_Transponder__
