#ifndef __RUPA_Burst_Editing_Add_Date__
#define __RUPA_Burst_Editing_Add_Date__

/**
@file
Subclass of Burst_Editing_Add_Date, which is generated by wxFormBuilder.
*/

#include "RUPAUI.h"

//// end generated include

/** Implementing Burst_Editing_Add_Date */
class RUPA_Burst_Editing_Add_Date : public Burst_Editing_Add_Date
{
	public:
		/** Constructor */
		RUPA_Burst_Editing_Add_Date( wxWindow* parent );
	//// end generated class members
	
};

#endif // __RUPA_Burst_Editing_Add_Date__
