#ifndef __RUPA_Burst_Editing__
#define __RUPA_Burst_Editing__

/**
@file
Subclass of Burst_Editing, which is generated by wxFormBuilder.
*/

#include "RUPAUI.h"
#include "RUPA_Utility.h"
#include "RUPA_Manage_Structure.h"

//// end generated include
class RUPA_Manage_Structure;
/** Implementing Burst_Editing */
class RUPA_Burst_Editing : public Burst_Editing
{
    protected:
	// Handlers for Burst_Editing events.
	void On_Add_Measure( wxCommandEvent& event );
	void On_Delete_Measure( wxCommandEvent& event );
	void On_Close( wxCommandEvent& event );

	sql::Driver *driver;
	sql::Connection *con;
	sql::Statement *stmt;
	sql::PreparedStatement *prep_stmt;
	sql::ResultSet *res;
	sql::ResultSet *res2;
	void Print_Measurement_Data_In_Table(wxListCtrl* Table, long int id_Structure, bool Recovery );
	RUPA_Manage_Structure * l_Manage_Structure;
	
	long int Id;
    public:
	/** Constructor */
	RUPA_Burst_Editing( wxWindow* parent, RUPA_Manage_Structure * MS, long int Burst_Id );
	void Refresh_Burst_Tables();
    //// end generated class members




};

#endif // __RUPA_Burst_Editing__
