#ifndef __RUPA_New_Campaign__
#define __RUPA_New_Campaign__

/**
@file
Subclass of New_Campaign, which is generated by wxFormBuilder.
*/

#include "RUPAUI.h"
#include "RUPA_Campaign.h"

class RUPA_Campaign;
//// end generated include

/** Implementing New_Campaign */
class RUPA_New_Campaign : public New_Campaign
{
    protected:
	// Handlers for New_Campaign events.
	void On_Install_Later( wxCommandEvent& event );
	void On_Install_Now( wxCommandEvent& event );
	void On_Cancel( wxCommandEvent& event );
	void Insert_Data();
	sql::Driver *driver;
	sql::Connection *con;
	sql::Statement *stmt;
	sql::PreparedStatement *prep_stmt;
	wxWindow* parent;
	RUPA_Campaign * l_Campaign;



    public:
	/** Constructor */
	RUPA_New_Campaign( wxWindow* parent, RUPA_Campaign * campaign );
	//~RUPA_New_Campaign( );
	//// end generated class members




};

extern watchdog_pi *g_watchdog_pi;
#endif // __RUPA_New_Campaign__
