#ifndef __watchdogDeadmanPanel__
#define __watchdogDeadmanPanel__

/**
@file
Subclass of DeadmanPanel, which is generated by wxFormBuilder.
*/

#include "WatchdogUI.h"

//// end generated include

/** Implementing DeadmanPanel */
class watchdogDeadmanPanel : public DeadmanPanel
{
	public:
		/** Constructor */
		watchdogDeadmanPanel( wxWindow* parent );
	//// end generated class members
	
};

#endif // __watchdogDeadmanPanel__
