#ifndef __watchdogSpeedPanel__
#define __watchdogSpeedPanel__

/**
@file
Subclass of SpeedPanel, which is generated by wxFormBuilder.
*/

#include "WatchdogUI.h"

//// end generated include

/** Implementing SpeedPanel */
class watchdogSpeedPanel : public SpeedPanel
{
	public:
		/** Constructor */
		watchdogSpeedPanel( wxWindow* parent );
	//// end generated class members
	
};

#endif // __watchdogSpeedPanel__
