#ifndef __watchdogLandFallPanel__
#define __watchdogLandFallPanel__

/**
@file
Subclass of LandFallPanel, which is generated by wxFormBuilder.
*/

#include "WatchdogUI.h"

//// end generated include

/** Implementing LandFallPanel */
class watchdogLandFallPanel : public LandFallPanel
{
	public:
		/** Constructor */
		watchdogLandFallPanel( wxWindow* parent );
	//// end generated class members
	
};

#endif // __watchdogLandFallPanel__
