#ifndef __watchdogConfigurationDialogBase__
#define __watchdogConfigurationDialogBase__

/**
@file
Subclass of ConfigurationDialogBase, which is generated by wxFormBuilder.
*/

#include "WatchdogUI.h"

//// end generated include

/** Implementing ConfigurationDialogBase */
class watchdogConfigurationDialogBase : public ConfigurationDialogBase
{
	protected:
		// Handlers for ConfigurationDialogBase events.
		void OnEnabled( wxCommandEvent& event );
		void OnNewAlarm( wxCommandEvent& event );
		void OnEditAlarm( wxCommandEvent& event );
		void OnDeleteAlarm( wxCommandEvent& event );
		void OnDeleteAllAlarms( wxCommandEvent& event );
		void OnDoubleClick( wxMouseEvent& event );
		void AlarmSelected( wxListEvent& event );
		void OnAboutAuthor( wxCommandEvent& event );
	public:
		/** Constructor */
		watchdogConfigurationDialogBase( wxWindow* parent );
	//// end generated class members
	
};

#endif // __watchdogConfigurationDialogBase__
