#ifndef __watchdogNMEADataPanel__
#define __watchdogNMEADataPanel__

/**
@file
Subclass of NMEADataPanel, which is generated by wxFormBuilder.
*/

#include "WatchdogUI.h"

//// end generated include

/** Implementing NMEADataPanel */
class watchdogNMEADataPanel : public NMEADataPanel
{
	public:
		/** Constructor */
		watchdogNMEADataPanel( wxWindow* parent );
	//// end generated class members
	
};

#endif // __watchdogNMEADataPanel__
