#ifndef __watchdogWatchdogPropertiesDialogBase__
#define __watchdogWatchdogPropertiesDialogBase__

/**
@file
Subclass of WatchdogPropertiesDialogBase, which is generated by wxFormBuilder.
*/

#include "WatchdogUI.h"

//// end generated include

/** Implementing WatchdogPropertiesDialogBase */
class watchdogWatchdogPropertiesDialogBase : public WatchdogPropertiesDialogBase
{
	protected:
		// Handlers for WatchdogPropertiesDialogBase events.
		void OnWatchdogPropertiesOKClick( wxCommandEvent& event );
	public:
		/** Constructor */
		watchdogWatchdogPropertiesDialogBase( wxWindow* parent );
	//// end generated class members
	
};

#endif // __watchdogWatchdogPropertiesDialogBase__
