#ifndef __watchdogBoundaryPanel__
#define __watchdogBoundaryPanel__

/**
@file
Subclass of BoundaryPanel, which is generated by wxFormBuilder.
*/

#include "WatchdogUI.h"

//// end generated include

/** Implementing BoundaryPanel */
class watchdogBoundaryPanel : public BoundaryPanel
{
	protected:
		// Handlers for BoundaryPanel events.
		void OnRadioButton( wxCommandEvent& event );
		void OnGuardZoneGUIDKillFocus( wxFocusEvent& event );
		void OnBoundaryGUIDKillFocus( wxFocusEvent& event );
		void OnGetBoundaryGUID( wxCommandEvent& event );
	public:
		/** Constructor */
		watchdogBoundaryPanel( wxWindow* parent );
	//// end generated class members
	
};

#endif // __watchdogBoundaryPanel__
