#ifndef __watchdogEditAlarmDialogBase__
#define __watchdogEditAlarmDialogBase__

/**
@file
Subclass of EditAlarmDialogBase, which is generated by wxFormBuilder.
*/

#include "WatchdogUI.h"

//// end generated include

/** Implementing EditAlarmDialogBase */
class watchdogEditAlarmDialogBase : public EditAlarmDialogBase
{
	protected:
		// Handlers for EditAlarmDialogBase events.
		void OnTestAlarm( wxCommandEvent& event );
		void OnInformation( wxCommandEvent& event );
	public:
		/** Constructor */
		watchdogEditAlarmDialogBase( wxWindow* parent );
	//// end generated class members
	
};

#endif // __watchdogEditAlarmDialogBase__
