#ifndef __watchdogCoursePanel__
#define __watchdogCoursePanel__

/**
@file
Subclass of CoursePanel, which is generated by wxFormBuilder.
*/

#include "WatchdogUI.h"

//// end generated include

/** Implementing CoursePanel */
class watchdogCoursePanel : public CoursePanel
{
	protected:
		// Handlers for CoursePanel events.
		void OnCurrentCourse( wxCommandEvent& event );
	public:
		/** Constructor */
		watchdogCoursePanel( wxWindow* parent );
	//// end generated class members
	
};

#endif // __watchdogCoursePanel__
