#ifndef __watchdogWatchdogDialogBase__
#define __watchdogWatchdogDialogBase__

/**
@file
Subclass of WatchdogDialogBase, which is generated by wxFormBuilder.
*/

#include "WatchdogUI.h"

//// end generated include

/** Implementing WatchdogDialogBase */
class watchdogWatchdogDialogBase : public WatchdogDialogBase
{
	protected:
		// Handlers for WatchdogDialogBase events.
		void OnDoubleClick( wxMouseEvent& event );
		void OnLeftDown( wxMouseEvent& event );
		void OnConfiguration( wxCommandEvent& event );
		void OnReset( wxCommandEvent& event );
		void OnClose( wxCommandEvent& event );
	public:
		/** Constructor */
		watchdogWatchdogDialogBase( wxWindow* parent );
	//// end generated class members
	
};

#endif // __watchdogWatchdogDialogBase__
