#ifndef __watchdogAnchorPanel__
#define __watchdogAnchorPanel__

/**
@file
Subclass of AnchorPanel, which is generated by wxFormBuilder.
*/

#include "WatchdogUI.h"

//// end generated include

/** Implementing AnchorPanel */
class watchdogAnchorPanel : public AnchorPanel
{
	protected:
		// Handlers for AnchorPanel events.
		void OnSyncToBoat( wxCommandEvent& event );
	public:
		/** Constructor */
		watchdogAnchorPanel( wxWindow* parent );
	//// end generated class members
	
};

#endif // __watchdogAnchorPanel__
