#ifndef __watchdogNewAlarmDialogBase__
#define __watchdogNewAlarmDialogBase__

/**
@file
Subclass of NewAlarmDialogBase, which is generated by wxFormBuilder.
*/

#include "WatchdogUI.h"

//// end generated include

/** Implementing NewAlarmDialogBase */
class watchdogNewAlarmDialogBase : public NewAlarmDialogBase
{
	protected:
		// Handlers for NewAlarmDialogBase events.
		void OnDoubleClick( wxMouseEvent& event );
	public:
		/** Constructor */
		watchdogNewAlarmDialogBase( wxWindow* parent );
	//// end generated class members
	
};

#endif // __watchdogNewAlarmDialogBase__
